apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-image
        ports:
        - containerPort: 8086
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-pv
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      initContainers:
        - name: cleaner
          image: cleaner-image
          volumeMounts:
          - name: influxdb-pv
            mountPath: /www
          imagePullPolicy: Never
