apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - nginx.yaml
  - phpmyadmin.yaml
  - wordpress.yaml
  - mysql.yaml
  - telegraf.yaml
  - influxdb.yaml
  - grafana.yaml
