apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - hop-sed-hop-sed

---

    apiVersion: v1
    kind: Service
    metadata:
      name: loadbalancer
    spec:
      selector:
        app: ft_services
      ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443
      - name: php
        protocol: TCP
        port: 5000
        targetPort: 5000
      - name: wordpress
        protocol: TCP
        port: 5050
        targetPort: 5050
      type: LoadBalancer
