# apiVersion: v1
# kind: ConfigMap
# metadata:
#   namespace: metallb-system
#   name: config
# data:
#   config: |
#     address-pools:
#     - name: default
#       protocol: layer2
#       addresses:
#       - 192.168.99.117-192.168.99.117
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    app: ft_services
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
  # apiVersion: v1
  # kind: Service
  # metadata:
  #   name: nginx
  # spec:
  #   selector:
  #     app: ft_services
  #     tier: nginx
  #     run: nginx
  #   ports:
  #   - name: http
  #     protocol: TCP
  #     port: 80
  #     targetPort: 80
  #   - name: https
  #     protocol: TCP
  #     port: 443
  #     targetPort: 443
  #   type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
  replicas: 1
  template:
    metadata:
      labels:
        app: ft_services
        tier: nginx
        run: nginx
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: nginx
        image: nginx-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-data
          mountPath: /www
        ports:
        - containerPort: 5050
      - name: phpmyadmin
        image: phpmyadmin-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      # - name: mysql
      #   image: mysql-image
      #   imagePullPolicy: Never
      #   # volumeMounts:
      #   # - name: mysql-data
      #   #   mountPath: /var/lib/mysql
      #   ports:
      #   - containerPort: 3306
      initContainers:
      - name: cleaner
        image: cleaner-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
