apiVersion: v1
kind: Service
metadata:
  name: a-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip : ft_services
spec:
  selector:
    app: ft_services
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/nginx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: ft_services
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
  replicas: 1
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: nginx-pv-claim
      containers:
      - name: nginx
        image: nginx-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
      initContainers:
      - name: cleaner
        image: cleaner-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
