apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  # annotations:
  #   metallb.universe.tf/allow-shared-ip : ft_services
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpmyadmin-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/phpmyadmin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      initContainers:
      - name: cleaner
        image: cleaner-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
