apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pidof telegraf
          initialDelaySeconds: 30
          periodSeconds: 2
