# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#     selector:
#       app: ft_services
#     ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80

#     - name: https
#       protocol: TCP
#       port: 443
#       targetPort: 443
# #   type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
  replicas: 2
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      # volumes:
      # - name: shared-data
      containers:
      - name: nginx
        image: nginx-image
        # volumeMounts:
        #   - name: shared-data
        #     mountPath: /var/www
        imagePullPolicy: Never
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 5000
      # - name: phpmyadmin
      #   image: phpmyadmin-image
      #   volumeMounts:
      #     - name: shared-data
      #       mountPath: /www
      #   imagePullPolicy: Never
      #   ports:
      #     - containerPort: 80
      #       hostPort: 5000
