apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf-image
        ports:
        - containerPort: 4999
        imagePullPolicy: Never

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-rbac
  namespace: default
rules:
- apiGroups: [ "", "extensions", "apps" ]
  resources: [ "daemonsets", "deployments", "endpoints", "ingresses", "nodes", "persistentvolumes", "persistentvolumeclaims", "pods", "services", "statefulsets" ]
  verbs: [ "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-rbac
  namespace: default
roleRef:
  kind: Role
  name: role-rbac
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
