apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip : ft_services
spec:
  selector:
    app: ft_services
  ports:
  - name: wordpress
    protocol: TCP
    port: 5050
    targetPort: 5050
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: ft_services
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
  replicas: 1
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
      containers:
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-data
          mountPath: /www
        ports:
        - containerPort: 5050
      initContainers:
      - name: cleaner
        image: cleaner-image
        volumeMounts:
        - name: shared-data
          mountPath: /www
        imagePullPolicy: Never
