FROM alpine
LABEL maintainer="leafney <babycoolzx@126.com>"

ENV MYSQL_VERSION=10.3.15-r0

RUN apk add --no-cache mysql mysql-client mariadb-server-utils bash && \
	mkdir /scripts && \
	rm -rf /var/cache/apk/*

COPY ./startup.sh /scripts/startup.sh
COPY my.cnf /etc/mysql/
RUN chmod +x /scripts/startup.sh

VOLUME ["/var/lib/mysql"]
EXPOSE 3306

ENTRYPOINT ["/scripts/startup.sh"]
