apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 127.0.0.3 - 127.0.0.3

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  #annotations:
  #  service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  #  service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
  #  service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"

spec:
  selector:
    app: ft-services
  ports:
      - port: 80
        targetPort: 80
        port: 443
        targetPort: 443
  externalTrafficPolicy: Local
  type: LoadBalancer
