kind: Service
apiVersion: v1
metadata:
    name: nginx-service
spec:
    selector:
        app: ft_services

    ports:
        - name: http
          port: 80
          targetPort: 80

          name: https
          port: 443
          targetPort: 443

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
  replicas: 3
  template:
    metadata:
      labels:
        app: ft_services
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443