FROM alpine

EXPOSE 80 443

RUN apk update
RUN apk add bash sed

# nginx set up
RUN apk add nginx \
&& adduser -D -g 'www' www \
&& mkdir /www \
&& chown -R www:www /var/lib/nginx \
&& mkdir /run/nginx
COPY nginx.conf /etc/nginx/nginx.conf

# ssl set up
RUN apk add openssl \
&& touch /etc/nginx/openssl.cnf \
&& cp /etc/ssl/openssl.cnf /etc/nginx/openssl.cnf \
&& mkdir -p /etc/ssl/private \
&& mkdir -p /etc/ssl/certs \
&& rm -rf /var/cache/apk/* \
&& openssl req \
  -x509 -nodes -days 3650 -newkey rsa:2048 \
  -subj "/CN=192.168.99.111" \
  -config /etc/nginx/openssl.cnf \
  -keyout /etc/ssl/private/self-signed.key \
  -out /etc/ssl/certs/self-signed.crt

COPY start.sh /
RUN chmod 755 /start.sh

CMD sh start.sh
