FROM alpine

EXPOSE 80 443

RUN apk update
RUN apk add bash sed

# nginx set up
RUN apk add nginx \
&& adduser -D -g 'www' www \
&& mkdir /www \
&& chown -R www:www /var/lib/nginx \
&& chown -R www:www /www
COPY nginx.conf /etc/nginx/nginx.conf

# php set up
RUN apk add php7-fpm php7-mcrypt php7-soap php7-openssl php7-gmp php7-pdo_odbc php7-json php7-dom php7-pdo php7-zip php7-mysqli php7-sqlite3 php7-apcu php7-pdo_pgsql php7-bcmath php7-gd php7-odbc php7-pdo_mysql php7-pdo_sqlite php7-gettext php7-xmlreader php7-xmlrpc php7-bz2 php7-iconv php7-pdo_dblib php7-curl php7-ctype \
&& export PHP_FPM_USER="www" \
&& export HP_FPM_GROUP="www" \
&& export PHP_FPM_LISTEN_MODE="0660" \
&& mkdir /run/nginx /run/php-fpm7 \
&& sed -i -e 's/listen = 127.0.0.1:9000/listen = hop-sed:9000/g' /etc/php7/php-fpm.d/www.conf;

# ssl set up
RUN apk add openssl \
&& touch /etc/nginx/openssl.cnf \
&& cp /etc/ssl/openssl.cnf /etc/nginx/openssl.cnf \
&& mkdir -p /etc/ssl/private \
&& mkdir -p /etc/ssl/certs \
&& openssl req \
  -x509 -nodes -days 3650 -newkey rsa:2048 \
  -subj "/CN=hop-sed" \
  -config /etc/nginx/openssl.cnf \
  -keyout /etc/ssl/private/self-signed.key \
  -out /etc/ssl/certs/self-signed.crt;

COPY 42.php /www/42.php
RUN echo "hop" > /www/hop.html;

CMD php-fpm7 && nginx -g "daemon off;"
