FROM alpine

RUN apk update
RUN apk add nginx
RUN apk add openssl
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir /run/nginx
RUN touch /etc/nginx/openssl.cnf
RUN cp /etc/ssl/openssl.cnf /etc/nginx/openssl.cnf
RUN mkdir -p /etc/ssl/private
RUN mkdir -p /etc/ssl/certs
RUN openssl req \
  -x509 -nodes -days 3650 -newkey rsa:2048 \
  -subj "/CN=localhost" \
  -config /etc/nginx/openssl.cnf \
  -keyout /etc/ssl/private/self-signed.key \
  -out /etc/ssl/certs/self-signed.crt;
RUN echo "42" > /var/www/42.html
EXPOSE 80 443
CMD nginx -g "daemon off;"
