FROM alpine
RUN apk add bash
RUN wget https://wordpress.org/latest.tar.gz -P /tmp \
&& mkdir /wordpress \
&& tar xzf /tmp/latest.tar.gz --strip-components=1 -C /wordpress\
&& mkdir /www
COPY wp-config.php /wordpress
EXPOSE 5050
CMD mv /wordpress /www
